package terminal

/*
type teaKey struct {
	Mod  tea.KeyMod
	Code rune
}

var keyTypeMap = map[teaKey]vterm.Key{
	{Code: 0}:                     vterm.KeyNone,
	{Code: 'c', Mod: tea.ModCtrl}: {Code: uint('c'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	{Code: tea.KeyEnter}:          vterm.KeyEnter,
	{Code: tea.KeyBackspace}:              vterm.KeyBackspace,
	tea.KeyTab:                    vterm.KeyTab,
	tea.KeyEsc:                    vterm.KeyEscape,

	tea.KeyCtrlA:            {Code: uint('a'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlB:            {Code: uint('b'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlD:            {Code: uint('d'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlE:            {Code: uint('e'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlF:            {Code: uint('f'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlG:            {Code: uint('g'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlH:            {Code: uint('h'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlJ:            {Code: uint('j'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlK:            {Code: uint('k'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlL:            {Code: uint('l'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlN:            {Code: uint('n'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlO:            {Code: uint('o'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlP:            {Code: uint('p'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlQ:            {Code: uint('q'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlR:            {Code: uint('r'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlS:            {Code: uint('s'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlT:            {Code: uint('t'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlU:            {Code: uint('u'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlV:            {Code: uint('v'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlW:            {Code: uint('w'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlX:            {Code: uint('x'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlY:            {Code: uint('y'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlZ:            {Code: uint('z'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlBackslash:    {Code: uint('\\'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlCloseBracket: {Code: uint(']'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlCaret:        {Code: uint('^'), Modifier: vterm.KeyModCtrl, IsUnichar: true},
	tea.KeyCtrlUnderscore:   {Code: uint('_'), Modifier: vterm.KeyModCtrl, IsUnichar: true},

	tea.KeyUp:         vterm.KeyUp,
	tea.KeyDown:       vterm.KeyDown,
	tea.KeyLeft:       vterm.KeyLeft,
	tea.KeyRight:      vterm.KeyRight,
	tea.KeyShiftTab:   {Code: vterm.KeyTab.Code, Modifier: vterm.KeyModShift},
	tea.KeyHome:       vterm.KeyHome,
	tea.KeyEnd:        vterm.KeyEnd,
	tea.KeyPgUp:       vterm.KeyPageup,
	tea.KeyPgDown:     vterm.KeyPagedown,
	tea.KeyCtrlPgUp:   {Code: vterm.KeyPageup.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyCtrlPgDown: {Code: vterm.KeyPagedown.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyDelete:     vterm.KeyDel,
	tea.KeyInsert:     vterm.KeyIns,
	tea.KeySpace:      {Code: uint(' '), IsUnichar: true},

	tea.KeyCtrlUp:    {Code: vterm.KeyUp.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyCtrlDown:  {Code: vterm.KeyDown.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyCtrlRight: {Code: vterm.KeyRight.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyCtrlLeft:  {Code: vterm.KeyLeft.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyCtrlHome:  {Code: vterm.KeyHome.Code, Modifier: vterm.KeyModCtrl},
	tea.KeyCtrlEnd:   {Code: vterm.KeyEnd.Code, Modifier: vterm.KeyModCtrl},

	tea.KeyShiftUp:    {Code: vterm.KeyUp.Code, Modifier: vterm.KeyModShift},
	tea.KeyShiftDown:  {Code: vterm.KeyDown.Code, Modifier: vterm.KeyModShift},
	tea.KeyShiftRight: {Code: vterm.KeyRight.Code, Modifier: vterm.KeyModShift},
	tea.KeyShiftLeft:  {Code: vterm.KeyLeft.Code, Modifier: vterm.KeyModShift},
	tea.KeyShiftHome:  {Code: vterm.KeyHome.Code, Modifier: vterm.KeyModShift},
	tea.KeyShiftEnd:   {Code: vterm.KeyEnd.Code, Modifier: vterm.KeyModShift},

	tea.KeyCtrlShiftUp:    {Code: vterm.KeyUp.Code, Modifier: vterm.KeyModCtrl | vterm.KeyModShift},
	tea.KeyCtrlShiftDown:  {Code: vterm.KeyDown.Code, Modifier: vterm.KeyModCtrl | vterm.KeyModShift},
	tea.KeyCtrlShiftLeft:  {Code: vterm.KeyLeft.Code, Modifier: vterm.KeyModCtrl | vterm.KeyModShift},
	tea.KeyCtrlShiftRight: {Code: vterm.KeyRight.Code, Modifier: vterm.KeyModCtrl | vterm.KeyModShift},
	tea.KeyCtrlShiftHome:  {Code: vterm.KeyHome.Code, Modifier: vterm.KeyModCtrl | vterm.KeyModShift},
	tea.KeyCtrlShiftEnd:   {Code: vterm.KeyEnd.Code, Modifier: vterm.KeyModCtrl | vterm.KeyModShift},

	tea.KeyF1:  {Code: vterm.KeyFunction0.Code + 1},
	tea.KeyF2:  {Code: vterm.KeyFunction0.Code + 2},
	tea.KeyF3:  {Code: vterm.KeyFunction0.Code + 3},
	tea.KeyF4:  {Code: vterm.KeyFunction0.Code + 4},
	tea.KeyF5:  {Code: vterm.KeyFunction0.Code + 5},
	tea.KeyF6:  {Code: vterm.KeyFunction0.Code + 6},
	tea.KeyF7:  {Code: vterm.KeyFunction0.Code + 7},
	tea.KeyF8:  {Code: vterm.KeyFunction0.Code + 8},
	tea.KeyF9:  {Code: vterm.KeyFunction0.Code + 9},
	tea.KeyF10: {Code: vterm.KeyFunction0.Code + 10},
	tea.KeyF11: {Code: vterm.KeyFunction0.Code + 11},
	tea.KeyF12: {Code: vterm.KeyFunction0.Code + 12},
	tea.KeyF13: {Code: vterm.KeyFunction0.Code + 13},
	tea.KeyF14: {Code: vterm.KeyFunction0.Code + 14},
	tea.KeyF15: {Code: vterm.KeyFunction0.Code + 15},
	tea.KeyF16: {Code: vterm.KeyFunction0.Code + 16},
	tea.KeyF17: {Code: vterm.KeyFunction0.Code + 17},
	tea.KeyF18: {Code: vterm.KeyFunction0.Code + 18},
	tea.KeyF19: {Code: vterm.KeyFunction0.Code + 19},
	tea.KeyF20: {Code: vterm.KeyFunction0.Code + 20},
}*/
